CREATE TABLE IF NOT EXISTS utenti(
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL, -- NUOVO CAMPO PER IL LOGIN
    email VARCHAR(100) UNIQUE NOT NULL,   -- Resta per contatti
    password VARCHAR(255) NOT NULL,
    nome VARCHAR(100) NOT NULL,
    cognome VARCHAR(100) NOT NULL,
    ruolo VARCHAR(20) NOT NULL CHECK (ruolo IN ('CLIENTE', 'ADMIN', 'PILOTA', 'HOSTESS'))
);

